//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieHachiTool.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tooloutput")]
        public string PictureHtmlExportPath {
            get {
                return ((string)(this["PictureHtmlExportPath"]));
            }
            set {
                this["PictureHtmlExportPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#出力フォルダ\r\n*outputfolder=A:\\Data\\20191221\\output\r\n#背景映像\r\n*bgi=Waves_5778.mp4\r\n#BGM\r" +
            "\n*bgm=bgm1.mp3,volume:33\r\n# キャラ：まとめなな\r\n*chara=まとめなな\r\n\r\n今日、3tene＋Nuitrackのツールでモーシ" +
            "ョンキャプチャしてみたよ。\r\n\r\n口パクモーションないけどごめんね。\r\n\r\nコメントで動きについてのツッコミよろしくね。\r\n\r\n今日、2019年12月21日のま" +
            "とめななのツッコミ。\r\n")]
        public string ScriptHeader {
            get {
                return ((string)(this["ScriptHeader"]));
            }
            set {
                this["ScriptHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("どうだったかな？\r\n\r\nちゃんねる登録よろしくねー。")]
        public string ScriptFooter {
            get {
                return ((string)(this["ScriptFooter"]));
            }
            set {
                this["ScriptFooter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("元ネタ.txt")]
        public string MotonetaTextFileName {
            get {
                return ((string)(this["MotonetaTextFileName"]));
            }
            set {
                this["MotonetaTextFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hachiシナリオ.txt")]
        public string ScripterOutputFileName {
            get {
                return ((string)(this["ScripterOutputFileName"]));
            }
            set {
                this["ScripterOutputFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("output")]
        public string HachiOutputFolderPath {
            get {
                return ((string)(this["HachiOutputFolderPath"]));
            }
            set {
                this["HachiOutputFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool URLPictureWriteYesNo {
            get {
                return ((bool)(this["URLPictureWriteYesNo"]));
            }
            set {
                this["URLPictureWriteYesNo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AfterOutputTextExecuteYesNo {
            get {
                return ((bool)(this["AfterOutputTextExecuteYesNo"]));
            }
            set {
                this["AfterOutputTextExecuteYesNo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FuriganaOutputYesNo {
            get {
                return ((bool)(this["FuriganaOutputYesNo"]));
            }
            set {
                this["FuriganaOutputYesNo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*fgi=切り替えワイプ.mp4,chromakey:440:1973:-321\r\n;;;;")]
        public string WipeText {
            get {
                return ((string)(this["WipeText"]));
            }
            set {
                this["WipeText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WipeYesNo {
            get {
                return ((bool)(this["WipeYesNo"]));
            }
            set {
                this["WipeYesNo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[image]")]
        public string ImageChangeText {
            get {
                return ((string)(this["ImageChangeText"]));
            }
            set {
                this["ImageChangeText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HGP創英角ﾎﾟｯﾌﾟ体, 20.25pt")]
        public global::System.Drawing.Font URLFont {
            get {
                return ((global::System.Drawing.Font)(this["URLFont"]));
            }
            set {
                this["URLFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HGP創英角ﾎﾟｯﾌﾟ体, 36pt")]
        public global::System.Drawing.Font TitleFont {
            get {
                return ((global::System.Drawing.Font)(this["TitleFont"]));
            }
            set {
                this["TitleFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("640, 0, 0, 0")]
        public global::System.Drawing.Rectangle TitleRectangle {
            get {
                return ((global::System.Drawing.Rectangle)(this["TitleRectangle"]));
            }
            set {
                this["TitleRectangle"] = value;
            }
        }
    }
}
